### PR TITLE
Feat/news

### LINKED ISSUE #58: Integrate the news API in the project

### PR DESCRIPTION
**Pull request by Saga-sanga**
Resolves #58

### CODE REVIEW

**Review by timothyrusso — CHANGES_REQUESTED** [review]
Something is broken in the mobile version of the project, I think it is better to solve it before merge this PR

**Comment by timothyrusso** [comment]
@Saga-sanga What do you think if we put the news component under the table of coins?

**Comment by Saga-sanga** [comment]
> Something is broken in the mobile version of the project, I think it is better to solve it before merge this PR

I've fixed that. Design should work properly on smaller screens now.

**Comment by timothyrusso** [comment]
@Saga-sanga Now it seams to work as expected, but now you need to resolve the conflicts and then we can see if everything work as expected before merge this PR

**Comment by Saga-sanga** [comment]
> @Saga-sanga What do you think if we put the news component under the table of coins?

We could find another place to put it if the current position doesn't work.

**Comment by timothyrusso** [comment]
@Saga-sanga now the LineChart is broken:

image

**Comment by timothyrusso** [comment]
@Saga-sanga my bad sorry, now it works!

**Review by timothyrusso — APPROVED** [review]

**Pull request merged**
