### PR TITLE
update code to render watchlist for specific user

### PR DESCRIPTION
**Pull request by DannyVogel**

### CODE REVIEW

**Comment by timothyrusso** [comment]
Hi @DannyVogel how can we register and login in the project?

**Comment by DannyVogel** [comment]
> 

go to the sign up page and sign up! that'll also log you in automatically so then you just click on dashboard to go back (pending implementing auto-redirect)

**Comment by timothyrusso** [comment]
@DannyVogel it works! But when I login, the site will not redirect to the dashboard home page, is this expected? Is it difficult to implement? Thanks!

**Comment by DannyVogel** [comment]
> @DannyVogel it works! But when I login, the site will not redirect to the dashboard home page, is this expected? Is it difficult to implement? Thanks!

this is expected. I am not familiar enough with React Router to implement it (assuming its needed).

**Comment by timothyrusso** [comment]
@DannyVogel if you want you can try use something like this:

```
  const navigate = useNavigate();
  const goToHomePage = () => navigate('/');
```

Then trigger the goToHomePage method after a successful login.

**Comment by DannyVogel** [comment]
> const navigate = useNavigate();
>   const goToHomePage = () => navigate('/');

for some reason the sign in component is a class component so I can't use hooks....

**Comment by DannyVogel** [comment]
> > const navigate = useNavigate();
> > const goToHomePage = () => navigate('/');
> 
> for some reason the sign in component is a class component so I can't use hooks....

I converted it to a functional component and now it says usenavigate isnt imported from react-router-dom. Might be using an older version...

**Comment by timothyrusso** [comment]
@DannyVogel yes I think you need to use the version 6, if this will create problem with you implementation don't worry don't do it.
Maybe we can implement only a little popup or something similar to show to the user that he is logged now.

**Comment by timothyrusso** [comment]
@DannyVogel I'll approve your PR, but I think we need to add another PR just to show to the user if he is logged or not

**Review by timothyrusso — APPROVED** [review]

**Pull request merged**
